[project]
name = "borrel"
version = "0.1.0"
description = ""
authors = [
    { name = "JRdeLange", email = "jordy.de.lange@planet.nl" }
]
readme = "README.md"
requires-python = "~=3.12"
dependencies = [
    "numpy==2.2.5",
    "pandas==2.2.3",
    "scipy==1.15.2",
    "ipykernel==6.29.5",
    "matplotlib==3.10.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"